
#include "bits/raylib.h"

#pragma minivm extern InitWindow "VMInitWindow"
#pragma minivm extern CloseWindow "VMCloseWindow"
#pragma minivm extern WindowShouldClose "VMWindowShouldClose"
#pragma minivm extern BeginDrawing "VMBeginDrawing"
#pragma minivm extern EndDrawing "VMEndDrawing"
#pragma minivm extern ClearBackground "VMClearBackground"
#pragma minivm extern IsKeyDown "VMIsKeyDown"
#pragma minivm extern IsKeyUp "VMIsKeyUp"
#pragma minivm extern IsKeyPressed "VMIsKeyPressed"
#pragma minivm extern IsKeyReleased "VMIsKeyReleased"
#pragma minivm extern DrawCircleV "VMDrawCircleV"
#pragma minivm extern SetTargetFPS "VMSetTargetFPS"
#pragma minivm extern DrawText "VMDrawText"
